spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/session
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8082

